let peliculasCartelera = [{
        id: 1,
        titulo: "Lightyear",
        anio: 2022,
        genero: "animación",
        duracion: "100min"
    },
    {
        id: 2,
        titulo: "El perro Samurai",
        anio: 2022,
        genero: "animación",
        duracion: "90min",
    },
    {
        id: 3,
        titulo: "DC Liga de Supermarscotas",
        anio: 2022,
        genero: "animación",
        duracion: "106min",
    },
    {
        id: 4,
        titulo: "Minions, nace un Villano",
        anio: 2022,
        genero: "animación",
        duracion: "87min",
    },
    {
        id: 5,
        titulo: "Toy Story 4",
        anio: 2022,
        genero: "animación",
        duracion: "90min",
    },
    {
        id: 6,
        titulo: "La ciudad perdida",
        anio: 2022,
        genero: "acción",
        duracion: "130min",
    },
    {
        id: 7,
        titulo: "Jurassic Worl Dominio",
        anio: 2022,
        genero: "aventuras",
        duracion: "128min",
    },
    {
        id: 8,
        titulo: "Tren bala",
        anio: 2022,
        genero: "acción",
        duracion: "126min",
    },
    {
        id: 9,
        titulo: "Top Gun, Maverick",
        anio: 2022,
        genero: "acción",
        duracion: "131min",
    },
    {
        id: 10,
        titulo: "Thor, el mundo oscuro ",
        anio: 2022,
        genero: "ciencia ficción",
        duracion: "128min",
    },
    {
        id: 11,
        titulo: "Perdiendo el norte",
        anio: 2022,
        genero: "comedia",
        duracion: "90min",
    },
    {
        id: 12,
        titulo: "30 noches con mi ex",
        anio: 2022,
        genero: "comedia",
        duracion: "95min",
    },
    {
        id: 13,
        titulo: "Buena suerte Leo",
        anio: 2022,
        genero: "comedia",
        duracion: "97min",
    },
    {
        id: 14,
        titulo: "El teléfono negro",
        anio: 2022,
        genero: "terror",
        duracion: "104min",
    },
    {
        id: 15,
        titulo: "La habitación del horror",
        anio: 2022,
        genero: "terror",
        duracion: "98min",
    },
]